---
title: "world-life-expectancy.csv"
output: 
  html:
    css: '../assets/codebooks.css'
    df_print: paged
    code_folding: show
theme: "yeti"
highlight-style: "atom-one"
bibliography: '../assets/epsy-5261.bib'
csl: '../assets/apa-single-spaced.csl'
---


```{r}
#| include: false
source("../assets/codebook-setup.R")
```


The [world-life-expectancy.csv](https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/world-life-expectancy.csv) data include information on the life expectancy for $N=207$ countries.

---

The attributes included in the data are:

- `country`: Country name
- `life_expect`: Life expectancy for all sexes (in years). This is the number of years a newborn infant would be expected to live if the current mortality rates at different ages were to stay the same.



---


### Preview

```{r}
# Import data
library(tidyverse)
world_life_expectancy <- read_csv(file = "https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/world-life-expectancy.csv")
```

```{r}
#| echo: false
# View data
DT::datatable(world_life_expectancy)
```


<!-- ### References -->



