---
title: "zillow-sample.csv"
output: 
  html:
    css: '../assets/codebooks.css'
    df_print: paged
    code_folding: show
theme: "yeti"
highlight-style: "atom-one"
bibliography: '../assets/epsy-5261.bib'
csl: '../assets/apa-single-spaced.csl'
---


```{r}
#| include: false
source("../assets/codebook-setup.R")
```


The [zillow-sample.csv](https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/zillow-sample.csv) data include information on $n=30$ house listings obtained from Zillow.com.
---

The attributes included in the data are:

- `price`: Listed price of the house
- `beds`: Number of bedrooms in the house
- `baths`: Number of bathrooms in the house
- `sqft`: Square footage of the liveable space in the house
- `age`: Age of the house (in years)



---


### Preview

```{r}
# Import data
library(tidyverse)
zillow_sample <- read_csv(file = "https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/zillow-sample.csv")
```

```{r}
#| echo: false
# View data
DT::datatable(zillow_sample)
```


<!-- ### References -->



