---
title: "body-temp.csv"
output: 
  html:
    css: '../assets/codebooks.css'
    df_print: paged
    code_folding: show
theme: "yeti"
highlight-style: "atom-one"
bibliography: '../assets/epsy-5261.bib'
csl: '../assets/apa-single-spaced.csl'
---


```{r}
#| include: false
source("../assets/codebook-setup.R")
```

The data in [body-temp.csv](https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/body-temp.csv) contains data simulated by @Shoemaker:1996 to match data presented in @Mackowiak:1992. The data include body temperatures and pulse rates for a sample of $n=50$ healthy adults. 

---

The attributes included in the data are:

- `temperature`: Body temperature (in degrees Fahrenheit)
- `pulse`: Pulse rate (beat per minute)
- `sex`: 1 = Female; 0 = Not female

---


### Preview

```{r}
#| eval: false
# Import data
library(tidyverse)
body_temp = read_csv(file = "https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/body-temps.csv")

# View data
body_temp
```

```{r}
#| echo: false
body_temp = readr::read_csv(file = "https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/body-temps.csv")
# View data
DT::datatable(body_temp)
```


### References



