<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>standardized-effects-props</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="07-05-standardized-effects-props_files/libs/clipboard/clipboard.min.js"></script>
<script src="07-05-standardized-effects-props_files/libs/quarto-html/quarto.js"></script>
<script src="07-05-standardized-effects-props_files/libs/quarto-html/popper.min.js"></script>
<script src="07-05-standardized-effects-props_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="07-05-standardized-effects-props_files/libs/quarto-html/anchor.min.js"></script>
<link href="07-05-standardized-effects-props_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="07-05-standardized-effects-props_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="07-05-standardized-effects-props_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="07-05-standardized-effects-props_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="07-05-standardized-effects-props_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<section id="sec-std-effects-props" class="level1">
<h1>Standardized Effects for Proportions</h1>
<p>In this chapter you will learn about using standardized effects for differences in proportions more interpretable.</p>
<p><br></p>
<section id="cohens-h" class="level2">
<h2 class="anchored" data-anchor-id="cohens-h">Cohen’s h</h2>
<p>There are several methods for computing standardizd effect sizes for differences in proportions. For example, Cohen (of Cohen’s <em>d</em> fame) developed a metric called Cohen’s <em>h</em>, which measures the distance between two proportions. This is based on an arcsine transformation of the proportions (remember your trigonometry??) and is computed as:</p>
<p><span class="math display">\[
h = 2 \arcsin(\sqrt{p_1}) – 2 \arcsin(\sqrt{p_2})
\]</span></p>
<p>where <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span> are the sample proportions you want to measure the effect between. We can illustrate how to compute this standardized effect using the <a href="https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/bachelor.csv">bachelor.csv</a> data to find Cohen’s <em>h</em> to between the proportion of Bachelor and Bachelorettes that are still together with their chosen suitors. Below we import the data and compute summary values for the two groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(educate)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggformula)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaicCore)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>bachelor <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/bachelor.csv"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># View data</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>bachelor</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 10
   show    season run_dates name    age winner runner_up proposal still_together
   &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt;         
 1 Bachel…      1 March 25… Alex…    31 Amand… Trista R… No       No            
 2 Bachel…      2 Septembe… Aaro…    28 Helen… Brooke S… Yes      No            
 3 Bachel…      3 March 24… Andr…    27 Jen S… Kirsten … Yes      No            
 4 Bachel…      4 Septembe… Bob …    32 Estel… Kelly Jo… No       No            
 5 Bachel…      5 April 7 … Jess…    25 Jessi… Tara Huc… No       No            
 6 Bachel…      6 Septembe… Byro…    40 Mary … Tanya Mi… Yes      No            
 7 Bachel…      7 March 28… Char…    29 Sarah… Krisily … No       No            
 8 Bachel…      8 January … Trav…    33 Sarah… Moana Di… No       No            
 9 Bachel…      9 October … Lore…    34 Jenni… Sadie Mu… No       No            
10 Bachel…     10 April 2 … Andy…    30 Tessa… Bevin Po… Yes      No            
# ℹ 40 more rows
# ℹ 1 more variable: relationship_status &lt;chr&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute proportions</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(<span class="sc">~</span>still_together <span class="sc">|</span> show, <span class="at">data =</span> bachelor, props)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Excluding 2 rows due to missing data [df_stats()].</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        response         show   prop_No  prop_Yes
1 still_together     Bachelor 0.8888889 0.1111111
2 still_together Bachelorette 0.8095238 0.1904762</code></pre>
</div>
</div>
<p>Based on the proportion that are still together, <span class="math inline">\(\hat{p}_{\text{Bachelor}} = .111, ~\hat{p}_{\text{Bachelorette}} = .174\)</span>, the difference is .063—this is a raw effect of the difference. To compute Cohen’s <em>h</em>, the standardized effect, we can employ those proportions in to the formula above. Because arcsine transformations might not be at the tip of your brain, we use R to do this with the function <code>asin()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute Cohen's h</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">asin</span>(<span class="fu">sqrt</span>(.<span class="dv">174</span>)) <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">asin</span>(<span class="fu">sqrt</span>(.<span class="dv">111</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1812569</code></pre>
</div>
</div>
<p>Cohen’s <em>h</em> value is .181. While the metric used for Cohen’s <em>h</em> is standardized, we typically don’t interpret the value; we just report it. We can, however, interpret the magnitude of Cohen’s <em>h</em> using the same guidelines as Cohen’s <em>d</em>:</p>
<p><span class="math display">\[
\begin{split}
h &amp;\approx 0.2 \qquad \text{Small Effect} \\[2ex]
h &amp;\approx 0.5 \qquad \text{Moderate Effect} \\[2ex]
h &amp;\approx 0.8 \qquad \text{Large Effect}
\end{split}
\]</span> In this example the difference between the two proportions indicates that it is a small effect.</p>
<p>Cohen’s <em>h</em> can also be computed when comparing a single sample proportion to a hypothesized proportion (one-sample situation). For example, in <strong>?@sec-one-sample-test-proportions</strong> we evaluated whether the proportion of all Minnesota children under 6 years of age who are above the MDH reference level in 2018 was different than 0.029 (the proportion in 2012).</p>
<p><br></p>
<section id="your-turn" class="level4 unnumbered exercises">
<h4 class="unnumbered anchored" data-anchor-id="your-turn">Your Turn</h4>
<p>Import the <a href="https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/fastx-reviews.csv">fastx-reviews.csv</a> data and compute the proportion of all critics’ “Fresh” reviews.</p>
<button class="solution-btn solution-btn-default" onclick="toggle_visibility('exercise_07-05-01');">
Show/Hide Solution
</button>
<div id="exercise_07-05-01" style="display:none; margin: -40px 0 40px 40px;">
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>fastx <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/fastx-reviews.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 238 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): reviewer, publication, score, fresh_rotten, review_text

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute sample proportion of Fresh reviews</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(<span class="sc">~</span>fresh_rotten, <span class="at">data =</span> fastx, props)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      response prop_fresh prop_rotten
1 fresh_rotten  0.5378151   0.4621849</code></pre>
</div>
</div>
</div>
<p>Use the <code>nrow()</code> function to compute the sample size. Just input the name of the data frame object into this function.</p>
<button class="solution-btn solution-btn-default" onclick="toggle_visibility('exercise_07-05-02');">
Show/Hide Solution
</button>
<div id="exercise_07-05-02" style="display:none; margin: -40px 0 40px 40px;">
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute sample size</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(fastx)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 238</code></pre>
</div>
</div>
</div>
<p>Use the formula (and R) to compute Cohen’s <em>h</em> comparing the sample proportion of “fresh” reviews to the hypothesized value of 0.5. Also indicate the magnitude of the effect based on Cohen’s guidelines.</p>
<button class="solution-btn solution-btn-default" onclick="toggle_visibility('exercise_07-05-03');">
Show/Hide Solution
</button>
<div id="exercise_07-05-03" style="display:none; margin: -40px 0 40px 40px;">
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute Cohen's h</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">asin</span>(<span class="fu">sqrt</span>(.<span class="dv">538</span>)) <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">asin</span>(<span class="fu">sqrt</span>(.<span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07607335</code></pre>
</div>
</div>
<p>An <em>h</em> of .076 is indicative of a very small effect.</p>
</div>
</section>
<p><br></p>
<section id="confidence-interval-for-cohens-h" class="level3">
<h3 class="anchored" data-anchor-id="confidence-interval-for-cohens-h">Confidence Interval for Cohen’s h</h3>
<p>The <code>ci_cohens_h()</code> function from the <code>{educate}</code> package can be used to find Cohen’s <em>h</em> and compute a confidence level for the population effect size. This function takes the following arguments:</p>
<ul>
<li><code>p1</code>: Proportion for Sample 1</li>
<li><code>n1</code>: Sample size for Sample 1</li>
<li><code>n1</code>: Proportion for Sample 2</li>
<li><code>n2</code>: Sample size for Sample 2</li>
<li><code>conf.level</code>: The confidence level for the interval (default is <code>conf.level = 0.95</code>)</li>
</ul>
<p>For example, to compute the 95% confidence interval for Cohen’s <em>h</em> in the population for our Bachelor/Bachelorette case study, we use the following syntax:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute CI for Cohen's h</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ci_cohens_h</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p1 =</span> <span class="fl">0.174</span>, <span class="co">#Proportion for Bachelorette</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n1 =</span> <span class="dv">25</span>,    <span class="co">#Sample size for Bachelorette</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">p2 =</span> .<span class="dv">111</span>,  <span class="co">#Proportion for Bachelor</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">n2 =</span> <span class="dv">27</span>,    <span class="co">#Sample size for Bachelor</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
--------------------------------------------------
95% Confidence Interval
--------------------------------------------------

Cohen's h = 0.09062846

Lower Limit = -0.3627418
Upper Limit = 0.7252556

--------------------------------------------------</code></pre>
</div>
</div>
<p>The CI is <span class="math inline">\([-0.36,~0.73]\)</span>, indicating tat Bachelorettes (numerator proportion) are between 0.79 and 3.11 times as likely to stay together as Bachelors (denominator proportion). Note that the lower limit is negative. This suggests that the proportion of Bachelors that stay together with their chosen suitor might be higher than the proportion of Bachelorettes that stay together with their chosen suitor. So, this CI is indicating that:</p>
<ul>
<li>There might be a somewhat small effect in the direction that the proportion of Bachelors that stay together with their chosen suitor might be higher than the proportion of Bachelorettes that stay together with their chosen suitor.</li>
<li>There might be no difference in the proportion of Bachelors and Bachelorettes that stay together with their chosen suitor, Or,</li>
<li>There might be a fairly large effect in the direction that the proportion of Bachelorettes that stay together with their chosen suitor might be higher than the proportion of Bachelors that stay together with their chosen suitor.</li>
</ul>
<div class="fyi">
<p>We can also use the <code>ci_cohens_h()</code> function to compare a single sample to a hypothesized value (e.g., finding the effect for a one-sample situation). To do this, whichever “sample” you use to input the hypothesized value (say <code>p2</code>), the corresponding sample size is inputted as <code>Inf</code> (i.e., <code>n2=Inf</code>). This ensures that only the actual sample summaries are used to compute the uncertainty in the CI.</p>
</div>
<p><br></p>
<section id="your-turn-1" class="level4 unnumbered exercises">
<h4 class="unnumbered anchored" data-anchor-id="your-turn-1">Your Turn</h4>
<p>Use the <code>ci_cohens_h()</code> function to compute the 95% confidence interval for the population effect in the Rotten Tomatoes example comparing to the hypothesized value of 0.5. For the sample size corresponding to the hypothesized value in the function, enter the value <code>Inf</code>.</p>
<button class="solution-btn solution-btn-default" onclick="toggle_visibility('exercise_07-05-04');">
Show/Hide Solution
</button>
<div id="exercise_07-05-04" style="display:none; margin: -40px 0 40px 40px;">
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute CI for Cohen's h</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ci_cohens_h</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p1 =</span> <span class="fl">0.538</span>, <span class="co">#Proportion for sample data</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n1 =</span> <span class="dv">238</span>,   <span class="co">#Sample size for sample data</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">p2 =</span> .<span class="dv">5</span>,    <span class="co">#Hypothesized proportion</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">n2 =</span> <span class="cn">Inf</span>,    <span class="co">#Hypothesized sample size</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
--------------------------------------------------
95% Confidence Interval
--------------------------------------------------

Cohen's h = 0.03803668

Lower Limit = -0.05097224
Upper Limit = 0.2031189

--------------------------------------------------</code></pre>
</div>
</div>
</div>
<p>Interpret the CI by commenting on the potential direction and magnitude of the effect.</p>
<button class="solution-btn solution-btn-default" onclick="toggle_visibility('exercise_07-05-05');">
Show/Hide Solution
</button>
<div id="exercise_07-05-05" style="display:none; margin: -40px 0 40px 40px;">
<p>The CI of <span class="math inline">\([-.05,~0.20]\)</span> indicates that:</p>
<ul>
<li>There might be a tiny effect in the direction that the proportion of “Fresh” reviews for Fast X may be less than 0.5.</li>
<li>It might be that the proportion of “Fresh” reviews for Fast X is 0.5.</li>
<li>There might be a small effect in the direction that the proportion of “Fresh” reviews for Fast X may be more than 0.5.</li>
</ul>
</div>
</section>
<p><br></p>
</section>
</section>
<section id="risk-ratio" class="level2">
<h2 class="anchored" data-anchor-id="risk-ratio">Risk Ratio</h2>
<p>A more commonly reported effect size is a <em>risk ratio</em>, also sometimes referred o as <em>relative risk</em>. This effect is most commonly used in medicine and health sciences, but is quite useful. A risk ratio measures the risk of a certain event happening in one group compared to the risk of the same event happening in another group. For example, a health research might compare the risk of COVID in low income communities to that in high income communities.</p>
<p>“Risk” is simply a proportion of something occurring in a group. In our Bachelor/Bachelorette example, “risk” might be staying together (or alternatively, breaking up). To compute the risk ratio, or relative risk, we are just computing the ratio of two proportions:</p>
<p><span class="math display">\[
\text{Risk Ratio} = \frac{p_1}{p_2}
\]</span> In our Bachelor/Bachelorette example the risk ratio of staying together is:</p>
<p><span class="math display">\[
\begin{split}
\text{Risk Ratio} &amp;= \frac{p_1}{p_2} \\[2ex]
&amp;= \frac{.174}{.111} \\[2ex]
&amp;= 1.56
\end{split}
\]</span> We can interpret this as Bachelorettes (numerator proportion) are 1.56 times as likely to stay together as Bachelors (denominator proportion).</p>
<div class="fyi">
<p>The choice of which group goes in the numerator is irrelevant. However, interpretationally it is easier if you put the bigger proportion in the numerator.</p>
</div>
<p><br></p>
<section id="risk-ratio-with-one-sample" class="level3">
<h3 class="anchored" data-anchor-id="risk-ratio-with-one-sample">Risk Ratio with One Sample</h3>
<p>We can also compute a risk ration when we only have a single sample. Rather than computing the ratio of two sample proportions, we compute the ratio of the sample proportion and the hypothesized value of <span class="math inline">\(\pi\)</span> tested in a hypothesis test.</p>
<p>As an example, consider the lead levels case study from <strong>?@sec-one-sample-test-proportions</strong>. We evaluated whether the the proportion of all Minnesota children under 6 years of age who are above the MDH reference level in 2018 different than .029 (the proportion in 2012?), by testing the following hypotheses:</p>
<p><span class="math display">\[
\begin{split}
H_0: \pi_{\text{Above MDH}} = .029 \\[1ex]
H_A: \pi_{\text{Above MDH}} \neq .029
\end{split}
\]</span></p>
<p>To compute a risk ratio, we import the data and compute numerical summaries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>mn_lead <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/mn-lead.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 91706 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): ebll
dbl (1): lead_level

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View data</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>mn_lead</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 91,706 × 2
   lead_level ebll 
        &lt;dbl&gt; &lt;chr&gt;
 1       2.39 No   
 2       2.42 No   
 3       3.73 No   
 4       3.53 No   
 5       2.6  No   
 6       1.8  No   
 7       4.46 No   
 8       3.77 No   
 9       2.03 No   
10       3.73 No   
# ℹ 91,696 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute numerical summaries</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(<span class="sc">~</span>ebll, <span class="at">data =</span> mn_lead, props)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  response  prop_No   prop_Yes
1     ebll 0.986086 0.01391403</code></pre>
</div>
</div>
<p>To compute the risk ratio:</p>
<p><span class="math display">\[
\begin{split}
\text{Risk Ratio} &amp;= \frac{p}{\pi} \\[2ex]
&amp;= \frac{.014}{.029} \\[2ex]
&amp;= 0.48
\end{split}
\]</span></p>
<p>We can interpret this as the proportion of all Minnesota children under 6 years of age who are above the MDH reference level in 2018 is less than half of that is 2012. Although typically we would put the larger number in the numerator, here we want to make the comparison back to the 2012 values, so we put that referent in the denominator. Remember, the choice of which value to put in the denominator is arbitrary—it just changes the interpretation.</p>
<p><br></p>
</section>
</section>
<section id="confidence-interval-for-risk-ratio" class="level2">
<h2 class="anchored" data-anchor-id="confidence-interval-for-risk-ratio">Confidence Interval for Risk Ratio</h2>
<p>We can compute a confidence interval for a risk ratio using the <code>ci_risk_ratio()</code> function from the <code>{educate}</code> package. This function takes the following arguments:</p>
<ul>
<li><code>p1</code>: Proportion for Sample 1</li>
<li><code>n1</code>: Sample size for Sample 1</li>
<li><code>n1</code>: Proportion for Sample 2</li>
<li><code>n2</code>: Sample size for Sample 2</li>
<li><code>conf.level</code>: The confidence level for the interval (default is <code>conf.level = 0.95</code>)</li>
</ul>
<p>For example, to compute the 95% confidence interval for the risk ratio in our Bachelor/Bachelorette case study, we use the following syntax:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute CI for risk ratio</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ci_risk_ratio</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p1 =</span> <span class="fl">0.174</span>, <span class="co">#Proportion for Bachelorette</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n1 =</span> <span class="dv">25</span>,    <span class="co">#Sample size for Bachelorette</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">p2 =</span> .<span class="dv">111</span>,  <span class="co">#Proportion for Bachelor</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">n2 =</span> <span class="dv">27</span>,    <span class="co">#Sample size for Bachelor</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
--------------------------------------------------
95% Confidence Interval
--------------------------------------------------

Risk Ratio = 1.567568

Lower Limit = 0.7941019
Upper Limit = 3.094399

--------------------------------------------------</code></pre>
</div>
</div>
<p>The CI is <span class="math inline">\([0.79,~3.09]\)</span>, indicating tat Bachelorettes (numerator proportion) are between 0.79 and 3.11 times as likely to stay together as Bachelors (denominator proportion). Note that the lower limit is below 1. This suggests that Bachelors are more likely than Bachelorettes to stay together with their chosen suitor. A risk ratio of 1 suggests that both groups are equally likely to stay together with their chosen suitor. So, this CI is indicating quite a lot of uncertainty:</p>
<ul>
<li>It may be that Bachelorettes are LESS likely than Bachelors to stay together with their chosen suitor (up to 0.79 times as likely).</li>
<li>It may be that both groups are EQUALLY likely to stay together with their chosen suitor. Or,</li>
<li>It may be that Bachelorettes are MORE likely than Bachelors to stay together with their chosen suitor (up to 3.09 times as likely).</li>
</ul>
<p><br></p>
<section id="using-conf_risk_ratio-with-a-single-sample" class="level3">
<h3 class="anchored" data-anchor-id="using-conf_risk_ratio-with-a-single-sample">Using <code>conf_risk_ratio()</code> With a Single Sample</h3>
<p>Use the <code>nrow()</code> function to compute the sample size.</p>
<button class="solution-btn solution-btn-default" onclick="toggle_visibility('exercise_07-05-07');">
Show/Hide Solution
</button>
<div id="exercise_07-05-07" style="display:none; margin: -40px 0 40px 40px;">
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute sample size</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(mn_lead)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 91706</code></pre>
</div>
</div>
</div>
<p>We can also use the <code>ci_risk_ratio()</code> function to compare a single sample to a hypothesized value (e.g., in our MN lead exposure case study). To do this, whichever “sample” you use to input the hypothesized value (say <code>p2</code>), the corresponding sample size is inputted as <code>Inf</code> (i.e., <code>n2=Inf</code>). This ensures that only the actual sample summaries are used to compute the uncertainty in the CI.</p>
<p>For example, to compute the CI for the risk ratio we computed earlier for the MN lead exposure example, we would input:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute CI for risk ratio</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ci_risk_ratio</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p1 =</span> <span class="fl">0.014</span>, <span class="co">#Sample proportion</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n1 =</span> <span class="dv">91706</span>,  <span class="co">#Sample size</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">p2 =</span> .<span class="dv">029</span>, <span class="co">#Hypothesized value</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">n2 =</span> <span class="cn">Inf</span>,   <span class="co">#Inf goes with the hypothesized value</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
--------------------------------------------------
95% Confidence Interval
--------------------------------------------------

Risk Ratio = 0.4827586

Lower Limit = 0.4698893
Upper Limit = 0.4959804

--------------------------------------------------</code></pre>
</div>
</div>
<p>The CI is <span class="math inline">\([0.470,~.496]\)</span>, indicating the proportion of all Minnesota children under 6 years of age who are above the MDH reference level in 2018 is between .470 and .496 times that in 2012. The high level of precision in the estimate is attributable to the large sample size, so we can say with some degree of certainty that the 2018 numbers are likely less than half of those in 2012.</p>
<p><br></p>
<section id="your-turn-2" class="level4 unnumbered exercises">
<h4 class="unnumbered anchored" data-anchor-id="your-turn-2">Your Turn</h4>
<p>Use the <code>ci_risk_ratio()</code> function to compute the risk ratio and the 99% CI for the population risk ratio that compares the proportion of “Fresh” reviews to the hypothesized value of 0.5.</p>
<button class="solution-btn solution-btn-default" onclick="toggle_visibility('exercise_07-05-06');">
Show/Hide Solution
</button>
<div id="exercise_07-05-06" style="display:none; margin: -40px 0 40px 40px;">
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute CI for risk ratio</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ci_risk_ratio</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p1 =</span> <span class="fl">0.537</span>, <span class="co">#Sample proportion</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n1 =</span> <span class="dv">238</span>,   <span class="co">#Sample size</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">p2 =</span> .<span class="dv">5</span>,    <span class="co">#Hypothesized value</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">n2 =</span> <span class="cn">Inf</span>,   <span class="co">#Inf goes with the hypothesized value</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.99</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
--------------------------------------------------
99% Confidence Interval
--------------------------------------------------

Risk Ratio = 1.074

Lower Limit = 1.011569
Upper Limit = 1.140284

--------------------------------------------------</code></pre>
</div>
</div>
</div>
<p>Interpret the confidence interval by commenting on the plausible values in the interval.</p>
<button class="solution-btn solution-btn-default" onclick="toggle_visibility('exercise_07-05-07');">
Show/Hide Solution
</button>
<div id="exercise_07-05-07" style="display:none; margin: -40px 0 40px 40px;">
<p>The CI is <span class="math inline">\([1.01,~1.14]\)</span> indicating that the proportion of “fresh” reviews is between 1.01 and 1.14 times higher than 0.5. While this suggests that Fast X will likely have more than half of its reviews rated as “fresh”, it won’t be much over half.</p>
</div>
</section>
<p><br></p>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>