project:
  type: book
  output-dir: docs
  preview:
    port: 4200
    browser: true
  resources: 
    - codebooks/ #Add codebooks to docs

book:
  title: "An Introduction to Data Analysis"
  author: ["Andrew Zieffler", "¢hel$ey £ega¢y"]
  date: "`r Sys.Date()`"
  sidebar:
    search: true
    background: "#0677a3"
  # cover-image: "figs/banner.png"
  chapters:
    - index.qmd
    - part: 01-00-statistical-computation.qmd
      chapters:
        - 01-01-r-and-rstudio-installation.qmd
        - 01-02-getting-started-with-r.qmd
        - 01-03-data-structures-in-r.qmd
    - part: 02-00-data.qmd
      chapters:
        - 02-01-data-structure-and-attributes.qmd
        # - 02-02-data-import.qmd
        # - 02-03-data-collection.qmd
    - part: 03-00-exploring-and-describing-data.qmd
      chapters:
        - 03-01-categorical-attributes.qmd
        - 03-02-quantitative-attributes.qmd
    - part: 04-00-comparing-to-a-standard.qmd
      chapters:
        - 04-01-case-study-teen-sleep.qmd
        - 04-02-simulation.qmd
        - 04-03-one-sample-test.qmd
        - 04-04-one-sample-test-computation.qmd
        - 04-05-one-sample-test-assumptions.qmd
        - 04-06-one-sample-test-proportions.qmd
    - part: 05-00-comparing-two-groups.qmd
      chapters:
        - 05-01-two-sample-t-test.qmd
        - 05-02-two-sample-test-assumptions.qmd
        - 05-03-two-sample-test-proportions.qmd
        - 05-04-errors.qmd
    - part: 06-00-study-design.qmd
      chapters:
        - 06-01-generalization.qmd
        - 06-02-cause-and-effect.qmd
    - part: 07-00-effect-size.qmd
      chapters:
        - 07-01-confidence-intervals.qmd
        - 07-02-confidence-intervals-computation.qmd
        - 07-03-confidence-intervals-extras.qmd
        - 07-04-standardized-effects-means.qmd
        - 07-05-standardized-effects-props.qmd
    - part: 08-00-relationships.qmd
      chapters:
        - 08-01-scatterplot-correlation.qmd
        - 08-02-linear-regression-description.qmd
        - 08-03-r-squared.qmd
        - 08-04-regression-inference.qmd
        
bibliography: ['assets/epsy-5261.bib']
csl: 'assets/apa-single-spaced.csl'
include-in-header: 'assets/epsy-5261.js'

format:
  html:
    theme: 
      - cosmo
      - "assets/theme.scss"
    css: ["assets/sticky-notes.css", "assets/table-styles.css"]
    code-copy: true
    highlight-style: zenburn
    df-print: paged
    mainfont: 'Crimson Text'
    fontsize: '12pt'
    linestretch: '1.5em'
    linkcolor: "#0099d4"

editor: source
