<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>An Introduction to Data Analysis: The End - 8&nbsp; One-Sample t-Test Using R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-05-one-sample-test-assumptions.html" rel="next">
<link href="./04-03-one-sample-test.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script type="text/javascript">
// Function to toggle the visibility of solutions in exercises
function toggle_visibility(id) {
   var e = document.getElementById(id);
   if(e.style.display == 'block')
      e.style.display = 'none';
   else
      e.style.display = 'block';
}
</script>

<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="assets/sticky-notes.css">
<link rel="stylesheet" href="assets/table-styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">One-Sample t-Test Using R</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">An Introduction to Data Analysis: The End</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Foreword</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./01-00-statistical-computation.html" class="sidebar-item-text sidebar-link">Statistical Computation</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-01-r-and-rstudio-installation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R and RStudio: Installation and Setup</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./02-00-data.html" class="sidebar-item-text sidebar-link">Data</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-01-data-structure-and-attributes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Structure and Attribute Classification</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03-00-exploring-and-describing-data.html" class="sidebar-item-text sidebar-link">Summarizing and Visualizing Data</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-01-categorical-attributes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summarizing and Visualizing Categorical Attributes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-02-quantitative-attributes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Summarizing and Visualizing Quantitative Attributes</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./04-00-comparing-to-a-standard.html" class="sidebar-item-text sidebar-link">Comparing Data to a Standard</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-01-case-study-teen-sleep.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Case Study: Teen Sleep</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-02-simulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Bootstrapping: Using Simulation to Estimate the Uncertainty</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-03-one-sample-test.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hypothesis Testing: One-Sample t-Test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-04-one-sample-test-computation.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">One-Sample t-Test Using R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-05-one-sample-test-assumptions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">One-Sample t-Test: Errors and Assumptions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-06-one-sample-test-proportions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">One-Sample z-Test: Evaluating Proportions Against a Standard</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#teen-sleep-a-quick-re-cap" id="toc-teen-sleep-a-quick-re-cap" class="nav-link active" data-scroll-target="#teen-sleep-a-quick-re-cap"><span class="toc-section-number">8.1</span>  Teen Sleep: A Quick Re-Cap</a></li>
  <li><a href="#using-the-t_test-function" id="toc-using-the-t_test-function" class="nav-link" data-scroll-target="#using-the-t_test-function"><span class="toc-section-number">8.2</span>  Using the <code>t_test()</code> Function</a></li>
  <li><a href="#case-study-2-continuous-assessment" id="toc-case-study-2-continuous-assessment" class="nav-link" data-scroll-target="#case-study-2-continuous-assessment"><span class="toc-section-number">8.3</span>  Case Study 2: Continuous Assessment</a></li>
  <li><a href="#case-study-house-prices" id="toc-case-study-house-prices" class="nav-link" data-scroll-target="#case-study-house-prices"><span class="toc-section-number">8.4</span>  Case Study: House Prices</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="toc-section-number">8.5</span>  References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-one-sample-test-r" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">One-Sample t-Test Using R</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In this chapter you will learn how to carry out a one-sample <em>t</em>-test using R to statistically compare a sample of data to a standard by accounting for the sampling uncertainty.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggformula)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>teen_sleep <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/teen-sleep.csv"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># View data</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>teen_sleep</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["bedtime"],"name":[1],"type":["chr"],"align":["left"]},{"label":["wakeup"],"name":[2],"type":["chr"],"align":["left"]},{"label":["hrs_sleep"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"22:15:00","2":"5:25:00","3":"7.166667"},{"1":"22:5:00","2":"5:50:00","3":"7.750000"},{"1":"22:15:00","2":"5:45:00","3":"7.500000"},{"1":"20:0:00","2":"6:20:00","3":"10.333333"},{"1":"23:45:00","2":"5:50:00","3":"6.083333"},{"1":"22:5:00","2":"6:0:00","3":"7.916667"},{"1":"0:25:00","2":"5:20:00","3":"4.916667"},{"1":"21:10:00","2":"6:15:00","3":"9.083333"},{"1":"21:20:00","2":"5:15:00","3":"7.916667"},{"1":"21:10:00","2":"5:30:00","3":"8.333333"},{"1":"22:50:00","2":"5:50:00","3":"7.000000"},{"1":"22:30:00","2":"5:50:00","3":"7.333333"},{"1":"23:35:00","2":"5:40:00","3":"6.083333"},{"1":"20:30:00","2":"6:15:00","3":"9.750000"},{"1":"20:40:00","2":"5:50:00","3":"9.166667"},{"1":"21:20:00","2":"5:45:00","3":"8.416667"},{"1":"23:35:00","2":"5:30:00","3":"5.916667"},{"1":"21:35:00","2":"6:5:00","3":"8.500000"},{"1":"22:5:00","2":"5:10:00","3":"7.083333"},{"1":"23:25:00","2":"7:20:00","3":"7.916667"},{"1":"23:25:00","2":"5:30:00","3":"6.083333"},{"1":"22:40:00","2":"6:15:00","3":"7.583333"},{"1":"0:30:00","2":"5:55:00","3":"5.416667"},{"1":"22:20:00","2":"6:15:00","3":"7.916667"},{"1":"22:55:00","2":"5:15:00","3":"6.333333"},{"1":"22:50:00","2":"5:30:00","3":"6.666667"},{"1":"22:20:00","2":"5:15:00","3":"6.916667"},{"1":"23:25:00","2":"5:55:00","3":"6.500000"},{"1":"22:35:00","2":"5:0:00","3":"6.416667"},{"1":"20:0:00","2":"5:55:00","3":"9.916667"},{"1":"21:5:00","2":"5:40:00","3":"8.583333"},{"1":"22:50:00","2":"6:55:00","3":"8.083333"},{"1":"20:30:00","2":"5:40:00","3":"9.166667"},{"1":"23:5:00","2":"5:40:00","3":"6.583333"},{"1":"21:50:00","2":"5:20:00","3":"7.500000"},{"1":"22:10:00","2":"5:35:00","3":"7.416667"},{"1":"1:5:00","2":"5:55:00","3":"4.833333"},{"1":"22:45:00","2":"6:5:00","3":"7.333333"},{"1":"22:50:00","2":"6:30:00","3":"7.666667"},{"1":"0:35:00","2":"6:25:00","3":"5.833333"},{"1":"1:30:00","2":"5:40:00","3":"4.166667"},{"1":"19:40:00","2":"6:45:00","3":"11.083333"},{"1":"0:0:00","2":"4:35:00","3":"4.583333"},{"1":"22:35:00","2":"6:10:00","3":"7.583333"},{"1":"21:40:00","2":"5:25:00","3":"7.750000"},{"1":"23:20:00","2":"6:40:00","3":"7.333333"},{"1":"1:0:00","2":"5:30:00","3":"4.500000"},{"1":"21:55:00","2":"6:40:00","3":"8.750000"},{"1":"22:5:00","2":"5:50:00","3":"7.750000"},{"1":"22:35:00","2":"4:30:00","3":"5.916667"},{"1":"0:50:00","2":"5:30:00","3":"4.666667"},{"1":"20:30:00","2":"4:35:00","3":"8.083333"},{"1":"22:50:00","2":"5:55:00","3":"7.083333"},{"1":"22:45:00","2":"7:5:00","3":"8.333333"},{"1":"23:50:00","2":"4:15:00","3":"4.416667"},{"1":"22:55:00","2":"6:25:00","3":"7.500000"},{"1":"22:5:00","2":"4:50:00","3":"6.750000"},{"1":"23:10:00","2":"7:0:00","3":"7.833333"},{"1":"22:55:00","2":"6:40:00","3":"7.750000"},{"1":"20:55:00","2":"5:10:00","3":"8.250000"},{"1":"21:0:00","2":"5:35:00","3":"8.583333"},{"1":"22:5:00","2":"5:45:00","3":"7.666667"},{"1":"18:25:00","2":"5:30:00","3":"11.083333"},{"1":"0:0:00","2":"7:30:00","3":"7.500000"},{"1":"20:55:00","2":"5:50:00","3":"8.916667"},{"1":"22:25:00","2":"5:15:00","3":"6.833333"},{"1":"21:50:00","2":"6:10:00","3":"8.333333"},{"1":"22:20:00","2":"5:55:00","3":"7.583333"},{"1":"22:50:00","2":"5:45:00","3":"6.916667"},{"1":"22:5:00","2":"5:40:00","3":"7.583333"},{"1":"21:15:00","2":"6:5:00","3":"8.833333"},{"1":"21:30:00","2":"5:5:00","3":"7.583333"},{"1":"0:20:00","2":"5:0:00","3":"4.666667"},{"1":"20:50:00","2":"6:55:00","3":"10.083333"},{"1":"23:15:00","2":"4:25:00","3":"5.166667"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p><br></p>
<section id="teen-sleep-a-quick-re-cap" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="teen-sleep-a-quick-re-cap"><span class="header-section-number">8.1</span> Teen Sleep: A Quick Re-Cap</h2>
<p>In this case study, researchers collected data on the bedtime, wake-up time, and hours slept for a sample of <span class="math inline">\(n=75\)</span> American teens in Grades 9–12. These data were used to evaluate the following statistical hypotheses For example, here are a set of potential hypotheses about teen sleep:</p>
<p><span class="math display">\[
\begin{split}
H_0: \mu = 9 \\[1ex]
H_A: \mu &lt; 9
\end{split}
\]</span> The analysis started by importing the data and visualizing and numerically describing the amopunt of sleep for the teens in our sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create density plot</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_density</span>(</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> hrs_sleep, <span class="at">data =</span> teen_sleep,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">color =</span> <span class="st">"black"</span>, </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">fill =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Hours of Sleep"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Density"</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute numerical summaries</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(<span class="sc">~</span>hrs_sleep, <span class="at">data =</span> teen_sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-hrs-sleep-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<div data-pagedtable="false">

<script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["response"],"name":[1],"type":["chr"],"align":["left"]},{"label":["min"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Q1"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["median"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Q3"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["max"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["mean"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["sd"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["n"],"name":[9],"type":["int"],"align":["right"]},{"label":["missing"],"name":[10],"type":["int"],"align":["right"]}],"data":[{"1":"hrs_sleep","2":"4.166667","3":"6.541667","4":"7.583333","5":"8.291667","6":"11.08333","7":"7.391111","8":"1.522724","9":"75","10":"0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.1: Density plot of the hours of sleep for 75 teenagers.</figcaption><p></p>
</figure>
</div>
<div class="cell-output-display">
<div id="fig-hrs-sleep-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-04-one-sample-test-computation_files/figure-html/fig-hrs-sleep-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.2: Density plot of the hours of sleep for 75 teenagers.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>These analyses suggest that, on average, the 75 teens in the sample are not getting the recommended 9 hours of sleep a night. They seem to be getting much less sleep on average, with a typical teen in the sample getting around 7.5 hours of sleep a night (<em>SD</em> = 1.5). To evaluate whether this lower amount of sleep we are seeing in the sample data is only a function of sampling uncertainty, we will carry out a one-sample <em>t</em>-test. To do this, we need to convert our sample mean to a <em>t</em>-value and then evaluate it in a <em>t</em>-distribution with <span class="math inline">\(n-1\)</span> <em>df</em>.</p>
<p><span class="math display">\[
t = \frac{\mathrm{Obs.~Mean} - \mathrm{Hyp.~Mean}}{SE}
\]</span></p>
<p>We have the observed mean (<span class="math inline">\(\bar{x}=7.39\)</span>), and the hypothesized mean (<span class="math inline">\(\mu=9\)</span>) from the data and null hypothesis, respectively. To obtain the <em>SE</em> we bootstrapped from the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw a bootstrap sample of 75 observations and compute the mean</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Do this 1000 times </span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign these into an object called bootstrap_means</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>bootstrap_means <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">1000</span>) <span class="sc">*</span> {<span class="fu">mean</span>(<span class="fu">sample</span>(teen_sleep<span class="sc">$</span>hrs_sleep, <span class="at">size =</span> <span class="dv">75</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>))}</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute numerical summaries to get SE</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(<span class="sc">~</span>result, <span class="at">data =</span> bootstrap_means)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["response"],"name":[1],"type":["chr"],"align":["left"]},{"label":["min"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Q1"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["median"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Q3"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["max"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["mean"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["sd"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["n"],"name":[9],"type":["int"],"align":["right"]},{"label":["missing"],"name":[10],"type":["int"],"align":["right"]}],"data":[{"1":"result","2":"6.837778","3":"7.278889","4":"7.391667","5":"7.509167","6":"8.023333","7":"7.395381","8":"0.1699168","9":"1000","10":"0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Based on the bootstrapping, the <em>SE</em> is 0.170. Putting this together, we compute the <em>t</em>-value as:</p>
<p><span class="math display">\[
\begin{split}
t &amp;= \frac{7.39 - 9}{.170} \\[2ex]
&amp;= -9.47
\end{split}
\]</span> We can then sketch the <em>t</em>-distribution with 74 <em>df</em>, include the <em>t</em>-value we just computed, and shade the area under the density plot that corresponds to the alternative hypothesis.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-t-dist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-04-one-sample-test-computation_files/figure-html/fig-t-dist-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.3: Density plot of the <em>t</em>-distribution of the sample means based on the thought experiment underlying a hypothesis test assuming that the mean amount of sleep for all tennagers is 9 hours (<em>t</em> value of 0). The blue shaded area represents the <em>t</em>-values we expect if the null hypothesis is true. The pink dot represents the observed <em>t</em>-value of -9.47.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The <em>p</em>-value (proportion of the pink shaded area to the whole area under the curve) is quite small. Because it is so small, it is difficult to even estimate its size—<span class="math inline">\(p&lt;.001\)</span>. This small <em>p</em>-value leads us to <em>reject the null hypothesis</em>, indicating that the data suggest that the average amount of sleep teens are getting is likely less than 9 hours and that this result is not only because of sampling uncertainty. That is, the empirical evidence is pointing us to the conclusion that teens are not getting the recommended amount of sleep.</p>
<p><br></p>
</section>
<section id="using-the-t_test-function" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="using-the-t_test-function"><span class="header-section-number">8.2</span> Using the <code>t_test()</code> Function</h2>
<p>Rather than bootstrapping the <em>SE</em>, we will use the <code>t_test()</code> function to compute the <em>SE</em> directly. This function is part of the <code>{mosaic}</code> library, and takes the following arguments:</p>
<ul>
<li>A formula using the tilde (<code>~</code>), similar to the <code>gf_</code> and <code>df_stats</code> functions, that specifies the attribute to carry out the one-sample <em>t</em>-test on.</li>
<li><code>data=</code> specifying the name of the data object,</li>
<li><code>mu=</code> indicating the value of the mean in the null hypothesis,</li>
<li><code>alternative=</code> indicating one of three potential alternative hypotheses: <code>"less"</code>, <code>"greater"</code>, or <code>"two.sided"</code> (not equal). Note that these need to be enclosed in quotation marks.</li>
</ul>
<p>To carry out the one-sample <em>t</em>-test in the earlier case study, we will use the following syntax. We assign the results of this <em>t</em>-test to an object (in this case, I called it <code>my_t</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-sample t-test</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>my_t <span class="ot">&lt;-</span> <span class="fu">t_test</span>(<span class="sc">~</span>hrs_sleep, <span class="at">data =</span> teen_sleep, <span class="at">mu =</span> <span class="dv">9</span>, <span class="at">alternative =</span> <span class="st">"less"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To see the results of the test, you can just call <code>my_t</code>, or whatever you named the object storing the <em>t</em>-test results. The output, however, is a bit unorganized. Instead, we are going to use two functions from the <code>{educate}</code> package to view the results of the <em>t</em>-test: <code>t_results()</code> and <code>plot_t_dist()</code>. To use these functions, we will need to load the <code>{educate}</code> library. Then, we can use each of these functions by supplying it with the name of the object storing our <em>t</em>-test results. We begin by using the <code>t_results()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load educate library</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(educate)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># View t-test results</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">t_results</span>(my_t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
--------------------------------------------------
One Sample t-test
--------------------------------------------------

H[0]: mu = 9
H[A]: mu &lt; 9

t(74) = -9.150303
p = 4.328872e-14

--------------------------------------------------</code></pre>
</div>
</div>
<p>This function outputs the null and alternative hypotheses being tested in the one-sample <em>t</em>-test. It also provide the observed <em>t</em>-value (<span class="math inline">\(-9.15\)</span>) and the <em>df</em> (74) for the <em>t</em>-distribution. Finally, it outputs the <em>p</em>-value for the test. When <em>p</em>-values are really small, R will output the <em>p</em>-value in <em>scientific notation</em>. The <code>e-14</code> part of the <em>p</em>-value means <span class="math inline">\(\times 10^{-14}\)</span>, which means, move the decimal point 14 places to the left. Thus the <em>p</em>-value is:</p>
<p><span class="math display">\[
\begin{split}
p &amp;= 4.328872 \times 10^{-14} \\[2ex]
&amp;= .0000000000000433
\end{split}
\]</span> Note that the <em>t</em>-value we get from this function was different than the <em>t</em>-value we got earlier. This is because the <em>SE</em> computed by the <code>t_test()</code> function is different than the <em>SE</em> we get when we bootstrap. Because of this, it is very important to indicate the method you used to get the <em>t</em>-value; was it based on bootstrapping a <em>SE</em>? Or did you use the <code>t_test()</code> function, which uses a <em>normal-based</em> method for computing the <em>SE</em>?</p>
<p>We can also use the <code>plot_t_dist()</code> to visualize the <em>t</em>-distribution with 74 <em>df</em>, where our observed <em>t</em>-value of <span class="math inline">\(-9.15\)</span>, falls in this distribution, and the shaded area under the curve associated with the <em>p</em>-value based on the specified alternative hypothesis. The results form the <em>t</em>-test will also be printed above the plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View t-distribution</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_t_dist</span>(my_t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-t-dist2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-04-one-sample-test-computation_files/figure-html/fig-t-dist2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.4: Density plot of the <em>t</em>-distribution of the sample means based on the thought experiment underlying a hypothesis test assuming that the mean amount of sleep for all tennagers is 9 hours (<em>t</em> value of 0). The red vertical line represents the observed <em>t</em>-value of -9.15. The shaded area under the curve to the left of -9.15 shows the associated <em>p</em>-value of <span class="math inline">\(4.33\times10^{-14} = .0000000000000433\)</span> that corresponds to the alternative hypothesis that <span class="math inline">\(\mu&lt;9\)</span>.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="case-study-2-continuous-assessment" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="case-study-2-continuous-assessment"><span class="header-section-number">8.3</span> Case Study 2: Continuous Assessment</h2>
<p>To study the practice of continuous assessment in Ethiopian primary schools, <span class="citation" data-cites="Abejehu:2016">Abejehu (<a href="#ref-Abejehu:2016" role="doc-biblioref">2016</a>)</span> collected survey responses from several primary school teachers. One tenet of continuous assessment is that to evaluate learning, teachers need to understand students’ prior knowledge. One item on the survey asked teachers about this: “I always assess students’ prior knowledge before starting new lesson.” Teachers responded on a Likert scale, with options: Strongly Agree (4), Agree (3), Disagree (2), and Strongly Disagree (1). The responses for 30 teachers is given in the <code>prior_knowledge</code> attribute of the <a href="https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/continuous-assessment.csv">continuous-assessment.csv</a> file (see <a href="https://zief0002.github.io/epsy-5261/codebooks/continuous-assessment.html">codebook</a> for additional detail).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>continuous_assessment <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/continuous-assessment.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 30 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (3): prior_knowledge, only_achievement, prompt_feedback

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View data</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>continuous_assessment</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["prior_knowledge"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["only_achievement"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["prompt_feedback"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"3","2":"2","3":"3"},{"1":"1","2":"3","3":"3"},{"1":"1","2":"2","3":"4"},{"1":"3","2":"3","3":"3"},{"1":"3","2":"4","3":"2"},{"1":"3","2":"3","3":"3"},{"1":"4","2":"2","3":"3"},{"1":"4","2":"3","3":"2"},{"1":"3","2":"3","3":"3"},{"1":"3","2":"3","3":"3"},{"1":"2","2":"3","3":"3"},{"1":"3","2":"3","3":"2"},{"1":"3","2":"4","3":"4"},{"1":"3","2":"2","3":"3"},{"1":"2","2":"2","3":"2"},{"1":"1","2":"1","3":"3"},{"1":"3","2":"3","3":"4"},{"1":"2","2":"3","3":"3"},{"1":"2","2":"2","3":"4"},{"1":"2","2":"2","3":"2"},{"1":"3","2":"2","3":"2"},{"1":"2","2":"3","3":"3"},{"1":"3","2":"2","3":"3"},{"1":"4","2":"3","3":"2"},{"1":"2","2":"2","3":"3"},{"1":"2","2":"4","3":"3"},{"1":"2","2":"1","3":"2"},{"1":"1","2":"3","3":"3"},{"1":"2","2":"2","3":"3"},{"1":"1","2":"3","3":"3"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>To evaluate whether Ethiopian primary teachers are measuring students’ prior knowledge, we will analyze the data in the <code>prior_knowledge</code> attribute. Because there is not substantive work on whether teachers actually do or do not assess students’ prior knowledge, we don’t have <em>a priori</em> conjectures about whether they will generally agree (3 or 4) or disagree (1 or 2) with the statement in the survey item. Because of that, we will examine the following set of potential hypotheses:</p>
<p><span class="math display">\[
\begin{split}
H_0: \mu = 2.5 \\[1ex]
H_A: \mu \neq 2.5
\end{split}
\]</span> Before we carry out a hypothesis test, we should always explore the data by creating visualizations and numerical summaries of the attribute. Because the data in the attribute is more discrete (can only be 1–4 with no values in between), we will create a histogram rather than a density plot of the responses. We will also set the <code>bins=</code> argument to <code>4</code> since there are only four possible response options.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create histogram</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_histogram</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>prior_knowledge, <span class="at">data =</span> continuous_assessment,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">bins =</span> <span class="dv">4</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">color =</span> <span class="st">"black"</span>, </span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">fill =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Level of Agreement"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Count"</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute numerical summaries</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(<span class="sc">~</span>prior_knowledge, <span class="at">data =</span> continuous_assessment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-prior-knowledge-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<div data-pagedtable="false">

<script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["response"],"name":[1],"type":["chr"],"align":["left"]},{"label":["min"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Q1"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["median"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Q3"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["max"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["mean"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["sd"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["n"],"name":[9],"type":["int"],"align":["right"]},{"label":["missing"],"name":[10],"type":["int"],"align":["right"]}],"data":[{"1":"prior_knowledge","2":"1","3":"2","4":"2.5","5":"3","6":"4","7":"2.433333","8":"0.8976342","9":"30","10":"0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.5: Histogram of teachers responses to the survey item: I always assess students’ prior knowledge before starting new lesson.</figcaption><p></p>
</figure>
</div>
<div class="cell-output-display">
<div id="fig-prior-knowledge-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-04-one-sample-test-computation_files/figure-html/fig-prior-knowledge-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.6: Histogram of teachers responses to the survey item: I always assess students’ prior knowledge before starting new lesson.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The histogram suggests that the distribution of responses is somewhat symmetric, with roughly an equal number of teachers assessing (3 and 4) and not assessing (1 and 2) students’ prior knowledge. Most teachers did not indicate strong agreement nor strong disagreement. The average response is 2.43, which indicates that a typical teacher does not assess students’ prior knowledge. However, the relatively large <em>SD</em> (0.90) suggests that there is a great deal of individual variation in the responses. Next, we carry out a one-sample <em>t</em>-test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-sample t-test</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>my_t <span class="ot">&lt;-</span> <span class="fu">t_test</span>(<span class="sc">~</span>prior_knowledge, <span class="at">data =</span> continuous_assessment, <span class="at">mu =</span> <span class="fl">2.5</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># View t-test results</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">t_results</span>(my_t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
--------------------------------------------------
One Sample t-test
--------------------------------------------------

H[0]: mu = 2.5
H[A]: mu ≠ 2.5

t(29) = -0.4067897
p = 0.6871492

--------------------------------------------------</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View t-distribution</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_t_dist</span>(my_t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-t-dist3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-04-one-sample-test-computation_files/figure-html/fig-t-dist3-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.7: Density plot of the <em>t</em>-distribution of the sample means based on the thought experiment underlying a hypothesis test assuming that the mean response for all Ethiopian primary school teachers is 2.5 (<em>t</em> value of 0). The red vertical line represents the observed <em>t</em>-value of -0.41. The shaded area under the curve to the left of -0.41 and to the right of +0.41 shows the associated <em>p</em>-value of .687 that corresponds to the alternative hypothesis that <span class="math inline">\(\mu eq2.5\)</span>.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Based on the <em>p</em>-value of .0687, we would <em>fail to reject</em> the null hypothesis. We do not have evidence that the average response for all Ethiopian primary school teachers differs from 2.5; that is the empirical data is consistent with the hypothesis that the average response for all Ethiopian primary school teachers is 2.5.</p>
<div class="fyi">
<p><strong>SUPER IMPORTANT NOTE</strong></p>
<p>Just because data are consistent with a hypothesis does not mean that hypothesis is true. As an example, consider a patient who goes to the doctor with a set of symptoms (e.g., aches, fever, congestion). The symptoms are the data the doctor will use to help make a diagnosis (hypothesis) which is consistent with the symptoms. However, there are likely several diagnoses that are consistent with the same set of symptoms. This is also true of hypotheses: The data can be consistent with several different hypotheses.</p>
<p>In our example, the data were consistent with the null hypothesis that the average response for all Ethiopian primary school teachers is 2.5. It turns out, that the data is also consistent with the hypothesis that the average response for all Ethiopian primary school teachers is 2.6. And 2.7, and 2.5. In fact, there are several different hypotheses that the data are consistent with. This is why we cannot say that the average response for all Ethiopian primary school teachers IS 2.5, but can only say that it IS CONSISTENT with the hypothesis that the average is 2.5.</p>
</div>
<p><br></p>
</section>
<section id="case-study-house-prices" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="case-study-house-prices"><span class="header-section-number">8.4</span> Case Study: House Prices</h2>
<p>The average price of a single-family house in Minneapolis is $322.46k (as of May 2023). Are houses near the University of Minnesota campus more expensive than that, on average? The data in <a href="https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/continuous-assessment.csv">zillow.csv</a> include the listing price (in thousands of dollars) for 15 houses in neighborhoods adjacent to the UMN campus (e.g., Como, Marcy-Holmes, Cedar-Riverside). We will use these data to evaluate the following hypotheses:</p>
<p><span class="math display">\[
\begin{split}
H_0: \mu = 322.46 \\[1ex]
H_A: \mu &gt; 322.46
\end{split}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-house-prices</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Histogram of the asking price for 15 houses in neighborhoods adjacent to the UMN campus. "</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co">#| </span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>zillow <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/zillow.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 15 Columns: 1
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (1): price

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View data</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>zillow</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["price"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"249.90"},{"1":"499.99"},{"1":"399.90"},{"1":"435.00"},{"1":"525.00"},{"1":"325.00"},{"1":"329.00"},{"1":"343.00"},{"1":"305.00"},{"1":"424.90"},{"1":"249.90"},{"1":"539.00"},{"1":"549.90"},{"1":"500.00"},{"1":"399.00"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create histogram</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_histogram</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>price, <span class="at">data =</span> zillow,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">binwidth =</span> <span class="dv">75</span>,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">color =</span> <span class="st">"black"</span>, </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">fill =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"House Price"</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Count"</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="04-04-one-sample-test-computation_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute numerical summaries</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>(<span class="sc">~</span>price, <span class="at">data =</span> zillow)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["response"],"name":[1],"type":["chr"],"align":["left"]},{"label":["min"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Q1"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["median"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Q3"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["max"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["mean"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["sd"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["n"],"name":[9],"type":["int"],"align":["right"]},{"label":["missing"],"name":[10],"type":["int"],"align":["right"]}],"data":[{"1":"price","2":"249.9","3":"327","4":"399.9","5":"499.995","6":"549.9","7":"404.966","8":"102.4312","9":"15","10":"0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The sample distribution is left-skewed indicating that more of the houses are at the higher and of the price range. A typical single-family house near the UMN campus costs a little over 400 thousand dollars (<em>M</em> = $404.97k). There is a lot of variation in house price, with some as low as $250k and others as high as $550k (<em>SD</em> = $102.43k). The sample evidence supports the hypothesis that the average price of a house near the UMN campus costs more than the average house in Minneapolis. Next, we will carry out a one-sample <em>t</em>-test to determine whether this difference is more than we expect because of sampling variation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-sample t-test</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>my_t <span class="ot">&lt;-</span> <span class="fu">t_test</span>(<span class="sc">~</span>price, <span class="at">data =</span> zillow, <span class="at">mu =</span> <span class="fl">322.46</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># View t-test results</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">t_results</span>(my_t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
--------------------------------------------------
One Sample t-test
--------------------------------------------------

H[0]: mu = 322.46
H[A]: mu &gt; 322.46

t(14) = 3.1196
p = 0.003766644

--------------------------------------------------</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View t-distribution</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_t_dist</span>(my_t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-t-dist4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-04-one-sample-test-computation_files/figure-html/fig-t-dist4-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.8: Density plot of the <em>t</em>-distribution of the sample means based on the thought experiment underlying a hypothesis test assuming that the mean cost for all houses near campus is $322.46k (<em>t</em> value of 0). The red vertical line represents the observed <em>t</em>-value of 3.12. The shaded area under the curve to the right of 3.12 shows the associated <em>p</em>-value of .004 that corresponds to the alternative hypothesis that <span class="math inline">\(\mu&gt;\$322.46k\)</span>.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The results of the <em>t</em>-test, <span class="math inline">\(t(14)=3.12\)</span>, <span class="math inline">\(p = .004\)</span>, indicate we should reject the null hypothesis. This suggests that the empirical evidence is consistent with the average cost of a house near the UMN campus being higher than the average cost of a house in Minneapolis more broadly.</p>
<p><br></p>
</section>
<section id="references" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="references"><span class="header-section-number">8.5</span> References</h2>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-Abejehu:2016" class="csl-entry" role="doc-biblioentry">
Abejehu, S. B. (2016). The <span>Practice</span> of <span>Continuous</span> <span>Assessment</span> in <span>Primary</span> <span>Schools</span>: <span>The</span> <span>Case</span> of <span>Chagni</span>, <span>Ethiopia</span>. <em>Journal of Education and Practice</em>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04-03-one-sample-test.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hypothesis Testing: One-Sample t-Test</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-05-one-sample-test-assumptions.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">One-Sample t-Test: Errors and Assumptions</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>